routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Apply coupon in the cart page
use App\Coupon;
use App\Http\Controllers\User\UserController;
use App\PercentOffCoupon;

// Coupon routes
Route::post('apply-coupon', 'Admin\CouponsController@applyCoupon')->name('applyCoupon');
Route::delete('/removeCoupon', 'Admin\CouponsController@removeCoupon')->name('removeCoupon');

// Admin routes
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/index', 'AdminController@admin')->name('admin');
    Route::resource('/products', 'ProductsController');
    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/{id}/edit', 'ReviewsController@edit')->name('reviews.edit');
    Route::delete('/reviews/{id}', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::get('/reviews/approved/{approved}', 'ReviewsController@approved')->name('reviews.approved');
    Route::post('/reviews/{id}', 'ReviewsController@update')->name('reviews.update');
    Route::get('/orders', 'OrdersController@index')->name('orders.index');
    Route::get('/orders/{id}/edit', 'OrdersController@edit')->name('orders.edit');
    Route::delete('/orders/{id}', 'OrdersController@destroy')->name('orders.destroy');
    Route::put('/orders/{id}', 'OrdersController@update')->name('orders.update');
    Route::resource('/categories', 'CategoriesController');
    Route::delete('/categories/product/{catid}/{proid}', 'CategoriesController@removeProductFromCategory')->name('category.product.remove');
    Route::resource('/attributes', 'AttributesController');
    Route::post('/attributevalues', 'AttributeValuesController@store')->name('attvalue.store');
    Route::delete('/attributevalues/{value}', 'AttributeValuesController@destroy')->name('attvalue.destroy');
    Route::get('/customers/subscribers', 'MailchimpController@index')->name('mailchimp.index');
    Route::resource('/coupons', 'CouponsController');
});

// Various pages routes
Route::get('/', 'PagesController@home')->name('home');
Route::get('/privacy-policy', 'PagesController@privacyPolicy');
Route::get('/terms-of-service', 'PagesController@termsOfService');
Route::get('/thank-you', 'Shop\ConfirmationController@index')->name('confirmation.index');

// Contact form
Route::get('contact', 'PagesController@getContact')->name('contact.index');
Route::post('sendcontact', 'PagesController@postContact')->name('contact.send');

// SHOP
Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
    Route::get('/', 'ShopController@index')->name('shop.index');
    Route::get('/{product}', 'ShopController@show')->name('shop.show');
});

//Review
Route::resource('review', 'Shop\ReviewController');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::post('/cart', 'CartController@store')->name('cart.store');
Route::delete('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
Route::patch('/cart/{product}', 'CartController@update')->name('cart.update');

// Favorite - wishlist
Route::post('/favorite/{product}', 'Shop\ShopController@favoriteProduct');
Route::post('/unfavorite/{product}', 'Shop\ShopController@unFavoriteProduct');
Route::get('/wishlist', 'Shop\ShopController@getWishList');

// Checkout page
Route::get('checkout', 'Shop\CheckoutController@index')->name('checkout.index');
Route::post('checkout', 'Shop\CheckoutController@store')->name('checkout.store');

// User profile
Route::group(['prefix' => 'user', 'middleware' => 'auth', 'namespace' => 'User'], function () {
    Route::get('/{id}/index', 'UserController@index')->name('user.index');
    Route::get('/{id}/info', 'UserController@info')->name('user.info');
    Route::get('/{id}/addresses', 'UserController@addresses')->name('user.addresses');
    Route::get('/{id}/orders', 'UserController@orders')->name('user.orders');
    Route::get('/{id}/subscriptions', 'UserController@subscription')->name('user.subscriptions');
    Route::post('/{id}/subscriptions', 'UserController@subscriptionPost')->name('user.subscriptions');
    Route::get('/{id}/wishlist', 'UserController@wishlist')->name('user.wishlist');
    Route::delete('/{id}/wishlist/{product}/remove', 'UserController@removeFromWishlist')->name('user.removeWProduct');
    Route::delete('/{id}/wishlist/clear', 'UserController@clearWishlist')->name('user.clearWishlist');
    Route::get('/{id}/orders/{orderid}/reorder', 'UserController@quickReorder')->name('user.reorder');
    Route::post('/{id}/info/update', 'UserController@userUpdate')->name('user.update');
});

// Auth
Auth::routes();
Route::get('admin/logout', 'Auth\LoginController@logout')->name('admin.logout');

// Social auth routes
Route::get('/auth/facebook/redirect', 'Auth\SocialAuthController@fbRedirect')->name('fb.redirect');
Route::get('/auth/facebook/callback', 'Auth\SocialAuthController@fbCallback');
Route::get('/auth/twitter/redirect', 'Auth\SocialAuthController@twRedirect')->name('tw.redirect');
Route::get('/auth/twitter/callback', 'Auth\SocialAuthController@twCallback');
Route::get('/auth/linkedin/redirect', 'Auth\SocialAuthController@ldRedirect')->name('ld.redirect');
Route::get('/auth/linkedin/callback', 'Auth\SocialAuthController@ldCallback');
Route::get('/auth/google/redirect', 'Auth\SocialAuthController@ggRedirect')->name('gg.redirect');
Route::get('/auth/google/callback', 'Auth\SocialAuthController@ggCallback');
Route::post('/subscribe', 'Admin\MailchimpController@store')->name('subscribe');
Route::get('/search/{term?}', 'Shop\ShopController@getSearchResults')->name('search.results');

// 302 redirects
Route::get('/admin', function () {
    return redirect()->route('admin');
});

resources/views/admin/layouts/includes/header.blade.php
<div class="header">
    <div class="row">
        <div class="container-fluid">
            <div class="section-subtitle">
                <h3>{{ $subtitle or "Dashboard" }}</h3>
            </div>
            <nav class="navbar-right">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="avatar"><img src="{{ auth()->user()->avatar }}" alt="" class="avatar"></div></li>
                    <li>{{ Auth::user()->name }}</li>
                    <li><a class="btn btn-primary" href="{{ route('admin.logout') }}"><i class="fas fa-sign-out-alt"></i>Logout</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

resources/views/admin/layouts/includes/sidenav.blade.php
<aside class="sidebar">
  @php
    $curl = url()->current();
  @endphp
  <div class="sidebar-head">
    <div id="logo">
      <a href="/admin"><img src="/images/logo-dash-light.png" alt="Logo"></a>
    </div>
  </div>
    <div id="leftside-navigation" class="nano">
  {{--<div>--}}
      <ul class="nano-content">
        <li class="<?php if(strpos($curl, 'index') !== false) echo "active" ?>">
          <a href="{{ Route('admin') }}">
              <i class="fas fa-home"></i><span>Dashboard</span>
          </a>
        </li>
        <li class="sub-menu <?php if(strpos($curl, 'products') !== false) echo "active selected" ?>">
          <a href="javascript:void(0);"><i class="fab fa-product-hunt"></i>
              <span>Products</span><i class="arrow fa fa-angle-right pull-right"></i>
          </a>
          <ul>
            <li><a href="{{Route('products.index')}}">All Products</a></li>
            <li><a href="{{Route('products.create')}}">Add New Product</a></li>

          </ul>
        </li>
        <li class="sub-menu <?php if(strpos($curl, 'categories') !== false) echo "active selected" ?>">
          <a href="javascript:void(0);"><i class="fa fa-table"></i><span>Categories</span><i class="arrow fa fa-angle-right pull-right"></i></a>
          <ul>
              <li><a href="{{ Route('categories.index') }}">All Categories</a></li>
              <li><a href="{{ Route('categories.create') }}">Add New Category</a></li>
          </ul>
        </li>
        <li class="sub-menu <?php if(strpos($curl, 'attributes') !== false) echo "active selected" ?>">
          <a href="javascript:void(0);"><i class="fa fa fa-tasks"></i><span>Attributes</span><i class="arrow fa fa-angle-right pull-right"></i></a>
          <ul>
            <li><a href="{{ route('attributes.index') }}">All Attributes</a>
            </li>
            <li>
              <a class="<?php if(strpos($curl, 'attributes/create') !== false) echo "active" ?>" href="{{ route('attributes.create') }}">Add New Attribute</a>
            </li>
          </ul>

        </li>
        <li class="sub-menu <?php if(strpos($curl, 'reviews') !== false) echo "active selected" ?>">
          <a href="javascript:void(0);"><i class="fa fa-envelope"></i><span>Reviews</span><i class="arrow fa fa-angle-right pull-right"></i></a>
          <ul>
            <li><a href="{{Route('reviews.index')}}">All Reviews</a></li>
            <li><a href="{{Route('reviews.approved', 1)}}">Approved</a></li>
            <li><a href="{{Route('reviews.approved', 0)}}">Not Approved</a></li>
          </ul>
        </li>
        <li class="sub-menu <?php if(strpos($curl, 'orders') !== false) echo "active selected" ?>">
          <a href="javascript:void(0);"><i class="fas fa-shopping-cart"></i><span>Sales</span><i class="arrow fa fa-angle-right pull-right"></i></a>
            <ul>
                <li><a href="{{ route('orders.index') }}">All Orders</a></li>
                {{-- <li><a href="{{ route('orders.index') }}">Invoices</a></li>
                <li><a href="{{ route('orders.index') }}">Return requests</a></li>
                <li><a href="{{ route('orders.index') }}">Gift cards</a></li>
                <li><a href="{{ route('orders.index') }}">Shipments</a></li> --}}
            </ul>
        </li>
        <li class="sub-menu">
          <a href="{{ route('coupons.index') }}"><i class="fas fa-tags"></i></i><span>Coupons</span></a>
        </li>
        <li class="sub-menu <?php if(strpos($curl, 'customers') !== false) echo "active selected" ?>">
          <a href="javascript:void(0);"><i class="fas fa-users"></i><span>Customers</span><i class="arrow fa fa-angle-right pull-right"></i></a>
            <ul>
                <li><a href="{{ route('mailchimp.index') }}"><span>Subscribers</span></a></li>
                {{-- <li><a href="{{ route('mailchimp.index') }}"><span>Customer Groups</span></a></li> --}}
                <li><a href="{{ route('mailchimp.index') }}"><span>Now Online</span></a></li>
            </ul>
        </li>
          <li class="sub-menu">
              <a href="{{ route('mailchimp.index') }}"><i class="fas fa-chart-line"></i><span>Reports</span></a>
          </li>
      </ul>

    </div>
  </aside>