routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Apply coupon in the cart page
use App\Coupon;
use App\Http\Controllers\User\UserController;
use App\PercentOffCoupon;

// Coupon routes
Route::post('apply-coupon', 'Admin\CouponsController@applyCoupon')->name('applyCoupon');
Route::delete('/removeCoupon', 'Admin\CouponsController@removeCoupon')->name('removeCoupon');

// Admin routes
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/index', 'AdminController@admin')->name('admin');
    Route::resource('/products', 'ProductsController');
    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/{id}/edit', 'ReviewsController@edit')->name('reviews.edit');
    Route::delete('/reviews/{id}', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::get('/reviews/approved/{approved}', 'ReviewsController@approved')->name('reviews.approved');
    Route::post('/reviews/{id}', 'ReviewsController@update')->name('reviews.update');
    Route::get('/orders', 'OrdersController@index')->name('orders.index');
    Route::get('/orders/{id}/edit', 'OrdersController@edit')->name('orders.edit');
    Route::delete('/orders/{id}', 'OrdersController@destroy')->name('orders.destroy');
    Route::put('/orders/{id}', 'OrdersController@update')->name('orders.update');
    Route::resource('/categories', 'CategoriesController');
    Route::delete('/categories/product/{catid}/{proid}', 'CategoriesController@removeProductFromCategory')->name('category.product.remove');
    Route::resource('/attributes', 'AttributesController');
    Route::post('/attributevalues', 'AttributeValuesController@store')->name('attvalue.store');
    Route::delete('/attributevalues/{value}', 'AttributeValuesController@destroy')->name('attvalue.destroy');
    Route::get('/customers/subscribers', 'MailchimpController@index')->name('mailchimp.index');
    Route::resource('/coupons', 'CouponsController');
});

// Various pages routes
Route::get('/', 'PagesController@home')->name('home');
Route::get('/privacy-policy', 'PagesController@privacyPolicy');
Route::get('/terms-of-service', 'PagesController@termsOfService');
Route::get('/thank-you', 'Shop\ConfirmationController@index')->name('confirmation.index');

// Contact form
Route::get('contact', 'PagesController@getContact')->name('contact.index');
Route::post('sendcontact', 'PagesController@postContact')->name('contact.send');

// SHOP
Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
    Route::get('/', 'ShopController@index')->name('shop.index');
    Route::get('/{product}', 'ShopController@show')->name('shop.show');
});

//Review
Route::resource('review', 'Shop\ReviewController');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::post('/cart', 'CartController@store')->name('cart.store');
Route::delete('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
Route::patch('/cart/{product}', 'CartController@update')->name('cart.update');

// Favorite - wishlist
Route::post('/favorite/{product}', 'Shop\ShopController@favoriteProduct');
Route::post('/unfavorite/{product}', 'Shop\ShopController@unFavoriteProduct');
Route::get('/wishlist', 'Shop\ShopController@getWishList');

// Checkout page
Route::get('checkout', 'Shop\CheckoutController@index')->name('checkout.index');
Route::post('checkout', 'Shop\CheckoutController@store')->name('checkout.store');

// User profile
Route::group(['prefix' => 'user', 'middleware' => 'auth', 'namespace' => 'User'], function () {
    Route::get('/{id}/index', 'UserController@index')->name('user.index');
    Route::get('/{id}/info', 'UserController@info')->name('user.info');
    Route::get('/{id}/addresses', 'UserController@addresses')->name('user.addresses');
    Route::get('/{id}/orders', 'UserController@orders')->name('user.orders');
    Route::get('/{id}/subscriptions', 'UserController@subscription')->name('user.subscriptions');
    Route::post('/{id}/subscriptions', 'UserController@subscriptionPost')->name('user.subscriptions');
    Route::get('/{id}/wishlist', 'UserController@wishlist')->name('user.wishlist');
    Route::delete('/{id}/wishlist/{product}/remove', 'UserController@removeFromWishlist')->name('user.removeWProduct');
    Route::delete('/{id}/wishlist/clear', 'UserController@clearWishlist')->name('user.clearWishlist');
    Route::get('/{id}/orders/{orderid}/reorder', 'UserController@quickReorder')->name('user.reorder');
    Route::post('/{id}/info/update', 'UserController@userUpdate')->name('user.update');
});

// Auth
Auth::routes();
Route::get('admin/logout', 'Auth\LoginController@logout')->name('admin.logout');

// Social auth routes
Route::get('/auth/facebook/redirect', 'Auth\SocialAuthController@fbRedirect')->name('fb.redirect');
Route::get('/auth/facebook/callback', 'Auth\SocialAuthController@fbCallback');
Route::get('/auth/twitter/redirect', 'Auth\SocialAuthController@twRedirect')->name('tw.redirect');
Route::get('/auth/twitter/callback', 'Auth\SocialAuthController@twCallback');
Route::get('/auth/linkedin/redirect', 'Auth\SocialAuthController@ldRedirect')->name('ld.redirect');
Route::get('/auth/linkedin/callback', 'Auth\SocialAuthController@ldCallback');
Route::get('/auth/google/redirect', 'Auth\SocialAuthController@ggRedirect')->name('gg.redirect');
Route::get('/auth/google/callback', 'Auth\SocialAuthController@ggCallback');
Route::post('/subscribe', 'Admin\MailchimpController@store')->name('subscribe');
Route::get('/search/{term?}', 'Shop\ShopController@getSearchResults')->name('search.results');

// 302 redirects
Route::get('/admin', function () {
    return redirect()->route('admin');
});

app/Attribute.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    protected $fillable = ['name'];

    public function values()
    {
        return $this->hasMany('App\AttributeValue');
    }
}

app/Http/Controllers/Admin/AttributesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Attribute;
use App\AttributeValue;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AttributesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attributes = Attribute::all();

        return view('admin.attributes.index', compact('attributes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.attributes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required|max:255',
            'value.*' => 'required|string'
        ]);

        $att = Attribute::create(['name' => $request->name]);
        if ($att) {
            foreach ($request->value as $val) {

                AttributeValue::create([
                    'value' => $val,
                    'attribute_id' => $att->id
                ]);
            }
        } else {
            return redirect()->back()->withErrors('This attribute already exists');
        }
        return redirect()->route('attributes.index')->withSuccessMessage('The new attribute is set!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $attribute = Attribute::find($id);

        return view('admin.attributes.edit', compact('attribute'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $att = Attribute::find($id);
        $att->name = $request->name;
        $att->save();
        return redirect()->back()->withSuccessMessage('Attribute name has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $att = Attribute::find($id);

        if ($att->delete()) {
            return redirect()->back()->withSuccessMessage('Attribute is deleted successfully!');
        }
        return redirect()->back();
    }
}

resources/views/admin/attributes/create.blade.php
@extends('admin.layouts.master', ['subtitle' => 'Create new Attribute', 'bodyClass' => 'attribute-create'])

@section('content')
    <section id="attribute-create">
        <div class="card card-big">
            <div class="card-body">
                <h5 class="card-title">Attributes</h5>
                <div class="row">
                <div class="col-sm-4">
                    <form action="{{ Route('attributes.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Attribute Name</label>
                            <input type="text" name="name" placeholder="name" required>
                        </div>
                        <div class="form-group">
                            {{--<label>Values:</label>--}}
                        </div>
                            <div id="attribute-values"></div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit" name="submit"><span><i class="fas fa-save"></i></span>Submit</button>
                        </div>
                    </form>
                </div>
                    <div class="col-sm-4">
                        <button id="create-input-field" class="btn btn-outline"><span><i class="fas fa-plus"></i></span>Add new value</button>
                    </div>
                </div>
            </div>

        </div>
    </section>

@endsection
@section('jsheader')
{{--    <script src="{{ asset('js/admin/header.js') }}"></script>--}}
@endsection

resources/views/admin/attributes/edit.blade.php
@extends('admin.layouts.master', ['subtitle' => 'Edit Attribute', 'bodyClass' => 'attribute-edit'])

@section('content')
    <section id="attribute-edit">
        <div class="card card-big">
            <div class="card-body">
                <a href="{{ route('attributes.index') }}" class="btn btn-outline-gray"><i class="fas fa-arrow-left"></i>Back</a>
                <h5 class="card-title">Edit Attribute {{ $attribute->name }}</h5>
                <div class="row">
                    <div class="col-sm-4">
                        <form action="{{ Route('attributes.update', $attribute->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="form-group">
                                <label for="name">Attribute Name</label>
                                <input type="text" name="name" placeholder="name" required value="{{ $attribute->name }}">
                            </div>

                            <div class="form-group">
                                <button class="btn btn-ok" type="submit" name="submit"><span><i class="fas fa-save"></i></span>Update Name</button>
                            </div>
                        </form>
                        @php
                            $atts = $attribute->values()->get();
                        @endphp
                        <br><br>
                        <hr>
                        <br>
                    <h5 class="card-title">Add New Value to {{ $attribute->name }} attribute</h5>

                        <form action="{{ Route('attvalue.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="name">Attribute Value</label>
                                <input type="text" name="value" placeholder="new value" required>
                            </div>
                            <input type="hidden" value="{{ $attribute->id }}" name="attribute_id">

                            <div class="form-group">
                                <button class="btn btn-primary" type="submit" name="submit"><span><i class="fas fa-save"></i></span>Save value</button>
                            </div>
                        </form>

                    </div>
                    <div class="col-sm-2 col-md-2">

                    </div>
                    <div class="col-sm-4 col-md-3">
                        <table class="table list-attributes">
                            <thead>
                                <th>Name</th>
                                <th>Actons</th>
                            </thead>
                            <tbody>
                            @foreach($atts as $att)
                                <tr>
                                    <td>{{ $att->value }}</td>
                                    <td class="table-actions">
                                        <form action="{{ route('attvalue.destroy', $att->id) }}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button type="submit"><i class="fas fa-trash-alt"></i>Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach


                            </tbody>
                        </table>

                    </div>

                </div>
            </div>

        </div>
    </section>

@endsection
@section('jsheader')

@endsection

resources/views/admin/attributes/index.blade.php
@extends('admin.layouts.master', ['subtitle' => 'Attributes'])

@section('content')
    <section id="attribute-list">
        <div class="card card-big">
            <div class="card-body">
                <h5 class="card-title">Attributes</h5>
                <div class="table-responsive">

                    @if($attributes->count())
                    <table class="table center-aligned-table list-attributes">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Values</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse ($attributes as $att)
                            <tr>
                                <td><span>{{ $att->name }}</span></td>
                                <td class="value-items">

                                    @forelse($att->values()->get() as $val)
                                        <span class="value-item">
                                            {{ $val->value }}
                                        </span>
                                    @empty
                                        <span>There is not values for this attribute yet.</span>
                                    @endforelse
                                </td>
                                <td class="table-actions">
                                    <a href="{{ route('attributes.edit', $att->id) }}" class="btn-sm"><i class="fas fa-edit"></i></a>
                                    <form action="{{ route('attributes.destroy', $att->id) }}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @empty



                        @endforelse
                        </tbody>
                    </table>
                    @else
                        There is no attributes yet.
                    @endif
                </div>
            </div>
            <a href="{{ route('attributes.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i>Create new Attribute</a>
        </div>
    </section>

@endsection