routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Apply coupon in the cart page
use App\Coupon;
use App\Http\Controllers\User\UserController;
use App\PercentOffCoupon;

// Coupon routes
Route::post('apply-coupon', 'Admin\CouponsController@applyCoupon')->name('applyCoupon');
Route::delete('/removeCoupon', 'Admin\CouponsController@removeCoupon')->name('removeCoupon');

// Admin routes
Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/index', 'AdminController@admin')->name('admin');
    Route::resource('/products', 'ProductsController');
    Route::get('/reviews', 'ReviewsController@index')->name('reviews.index');
    Route::get('/reviews/{id}/edit', 'ReviewsController@edit')->name('reviews.edit');
    Route::delete('/reviews/{id}', 'ReviewsController@destroy')->name('reviews.destroy');
    Route::get('/reviews/approved/{approved}', 'ReviewsController@approved')->name('reviews.approved');
    Route::post('/reviews/{id}', 'ReviewsController@update')->name('reviews.update');
    Route::get('/orders', 'OrdersController@index')->name('orders.index');
    Route::get('/orders/{id}/edit', 'OrdersController@edit')->name('orders.edit');
    Route::delete('/orders/{id}', 'OrdersController@destroy')->name('orders.destroy');
    Route::put('/orders/{id}', 'OrdersController@update')->name('orders.update');
    Route::resource('/categories', 'CategoriesController');
    Route::delete('/categories/product/{catid}/{proid}', 'CategoriesController@removeProductFromCategory')->name('category.product.remove');
    Route::resource('/attributes', 'AttributesController');
    Route::post('/attributevalues', 'AttributeValuesController@store')->name('attvalue.store');
    Route::delete('/attributevalues/{value}', 'AttributeValuesController@destroy')->name('attvalue.destroy');
    Route::get('/customers/subscribers', 'MailchimpController@index')->name('mailchimp.index');
    Route::resource('/coupons', 'CouponsController');
});

// Various pages routes
Route::get('/', 'PagesController@home')->name('home');
Route::get('/privacy-policy', 'PagesController@privacyPolicy');
Route::get('/terms-of-service', 'PagesController@termsOfService');
Route::get('/thank-you', 'Shop\ConfirmationController@index')->name('confirmation.index');

// Contact form
Route::get('contact', 'PagesController@getContact')->name('contact.index');
Route::post('sendcontact', 'PagesController@postContact')->name('contact.send');

// SHOP
Route::group(['prefix' => 'shop', 'namespace' => 'Shop'], function () {
    Route::get('/', 'ShopController@index')->name('shop.index');
    Route::get('/{product}', 'ShopController@show')->name('shop.show');
});

//Review
Route::resource('review', 'Shop\ReviewController');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::post('/cart', 'CartController@store')->name('cart.store');
Route::delete('/cart/{product}', 'CartController@destroy')->name('cart.destroy');
Route::patch('/cart/{product}', 'CartController@update')->name('cart.update');

// Favorite - wishlist
Route::post('/favorite/{product}', 'Shop\ShopController@favoriteProduct');
Route::post('/unfavorite/{product}', 'Shop\ShopController@unFavoriteProduct');
Route::get('/wishlist', 'Shop\ShopController@getWishList');

// Checkout page
Route::get('checkout', 'Shop\CheckoutController@index')->name('checkout.index');
Route::post('checkout', 'Shop\CheckoutController@store')->name('checkout.store');

// User profile
Route::group(['prefix' => 'user', 'middleware' => 'auth', 'namespace' => 'User'], function () {
    Route::get('/{id}/index', 'UserController@index')->name('user.index');
    Route::get('/{id}/info', 'UserController@info')->name('user.info');
    Route::get('/{id}/addresses', 'UserController@addresses')->name('user.addresses');
    Route::get('/{id}/orders', 'UserController@orders')->name('user.orders');
    Route::get('/{id}/subscriptions', 'UserController@subscription')->name('user.subscriptions');
    Route::post('/{id}/subscriptions', 'UserController@subscriptionPost')->name('user.subscriptions');
    Route::get('/{id}/wishlist', 'UserController@wishlist')->name('user.wishlist');
    Route::delete('/{id}/wishlist/{product}/remove', 'UserController@removeFromWishlist')->name('user.removeWProduct');
    Route::delete('/{id}/wishlist/clear', 'UserController@clearWishlist')->name('user.clearWishlist');
    Route::get('/{id}/orders/{orderid}/reorder', 'UserController@quickReorder')->name('user.reorder');
    Route::post('/{id}/info/update', 'UserController@userUpdate')->name('user.update');
});

// Auth
Auth::routes();
Route::get('admin/logout', 'Auth\LoginController@logout')->name('admin.logout');

// Social auth routes
Route::get('/auth/facebook/redirect', 'Auth\SocialAuthController@fbRedirect')->name('fb.redirect');
Route::get('/auth/facebook/callback', 'Auth\SocialAuthController@fbCallback');
Route::get('/auth/twitter/redirect', 'Auth\SocialAuthController@twRedirect')->name('tw.redirect');
Route::get('/auth/twitter/callback', 'Auth\SocialAuthController@twCallback');
Route::get('/auth/linkedin/redirect', 'Auth\SocialAuthController@ldRedirect')->name('ld.redirect');
Route::get('/auth/linkedin/callback', 'Auth\SocialAuthController@ldCallback');
Route::get('/auth/google/redirect', 'Auth\SocialAuthController@ggRedirect')->name('gg.redirect');
Route::get('/auth/google/callback', 'Auth\SocialAuthController@ggCallback');
Route::post('/subscribe', 'Admin\MailchimpController@store')->name('subscribe');
Route::get('/search/{term?}', 'Shop\ShopController@getSearchResults')->name('search.results');

// 302 redirects
Route::get('/admin', function () {
    return redirect()->route('admin');
});

app/Category.php
<?php

namespace App;

use App\Product;
use Kalnoy\Nestedset\NodeTrait;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use NodeTrait;
    protected $fillable = ['name', 'parent_id'];

    public function products()
    {
        return $this->belongsToMany('App\Product')->withTimestamps();
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Mockery\Exception;

class CategoriesController extends Controller
{
    /**
     * Display a listing of categories.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = collect(Category::all()->toTree());
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new category.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = collect(Category::all());
        return view('admin.categories.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'slug' => 'required|string|unique:categories|max:255',
            'parent_id' => 'required'
        ]);
        if ($request->parent_id == 'root') {
            $node = new Category();
            $node->name = $request->name;
            $node->slug = $request->slug;
            $node->save();
            return redirect()->route('categories.index')->withSuccessMessage('Category has been sucessfully saved!');
        }
        $parent = Category::find($request->parent_id);
        $node = new Category();
        $node->name = $request->name;
        $node->slug = $request->slug;
        $node->appendToNode($parent)->save();

        return redirect()->route('categories.index')->withSuccessMessage('Category has been sucessfully saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $products = Category::find($id)->products;
        $categories = Category::all();
        return view('admin.categories.index', compact(['products', 'categories']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Category::find($id)->products;
        $category = Category::find($id);
        $categories = Category::all();
        return view('admin.categories.edit', compact(['products', 'category', 'categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'name' => 'required',
            //            'slug' => 'required|unique:categories',
            'slug' => 'required',
        ]);

        $cat = Category::find($id);
        $cat->name = $request->name;
        $cat->slug = $request->slug;
        $cat->save();
        return redirect()->back()->with('success_message', 'Category has been successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = Category::find($id);

        if ($cat->delete()) {
            $categories = collect(Category::all()->toTree());
            return redirect()->route('categories.index')->with('categories', $categories)->withSuccessMessage('Category ' . $cat->name . ' has been removed');
        }
        $categories = collect(Category::all()->toTree());
        return redirect()->route('categories.index')->with('categories', $categories)->withErrors('Some errors has appear! Please try again.');
    }
    /**
     * Remove the specified product from the category.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function removeProductFromCategory($proid, $catid)
    {
        $cat = Category::find($catid);
        try {
            $cat->products()->detach($proid);
        } catch (Exception $e) {
            return redirect()->back()->withErrors($e->getMessage());
        }
        return redirect()->back()->with('success_message', 'Product has been removed');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

@section('content')
    <section id="attribute-list">
        <div class="card card-big">
            <div class="card-body">
            <h5 class="cart-title">Add New Category</h5>
            <div class="row">
                <div class="col-sm-4">
                    <form action="{{ Route('categories.store') }}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="name">Category Name</label>
                            <input type="text" name="name" placeholder="name" required value="{{ old('name')}}">
                        </div>
                        <div class="form-group">
                                <label for="name">Category Slug</label>
                                <input type="text" name="slug" placeholder="slug" required value="{{ old('slug')}}">
                            </div>
                        <div class="form-group">
                            <label for="name">Category parent</label>
                            <select name="parent_id" id="parent_id">
                                <option value="root">No parent (root)</option>
                                @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }} ({{ $category->slug }})</option>
                                @endforeach
                            </select>
                        </div>
                        <button class="btn btn-primary" type="submit" name="submit"><i class="fas fa-save"></i>Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master', ['subtitle'=>'Edit category', 'bodyClass' => 'edit-category'])

@section('content')
        <div class="card card-big">
            <div class="card-body">
                <div class="top-button-actions">
                    <a href="{{ route('categories.index') }}" class="btn btn-outline-gray"><i class="fas fa-arrow-left"></i>Back</a>
                </div>
                <h5 class="card-title">Edit category: {{ $category->name }}</h5>
                <div class="col-sm-6">
                    <form action="{{ Route('categories.update', $category->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Category Name</label>
                            <input type="text" name="name" placeholder="name" value="{{ $category->name }}">
                        </div>
                        <div class="form-group">
                            <label for="slug">Category slug</label>
                            <input type="text" name="slug" placeholder="slug" value="{{ $category->slug }}">
                        </div>
                        <div class="form-group">
                            <label for="parent_id">Parent category</label>
                            <select type="text" name="parent_id" id="select-id" disabled>

                                    @if(!$category->parent_id)
                                        <option value="" selected>{{$category->name}} is already root category</option>
                                    @endif
                                @foreach($categories as $cat)
                                {{-- remove current category from the list --}}
                                    @if($cat->id != $category->id)
                                            <option value="{{ $cat->id }}"
                                            @if($cat->id == $category->parent_id)
                                                selected="selected"
                                            @endif
                                            >{{ $cat->name }} [{{ $cat->slug }}]</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>

                        <input class="btn btn-primary" type="submit" value="Update" name="submit">
                    </form>
                    <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type="submit" class="btn btn-outline btn-danger" onclick="return confirm('Are you sure?')"><i class="fas fa-trash-alt"></i> Remove</button>
                    </form>

                </div>
            </div>
        </div>
        <div class="card card-big">
            <div class="card-body">
                <h5 class="card-title">Category products</h5>
                <div class="table-responsive">
                    @if(count($products) > 0)

                    <table class="table center-aligned-table list">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Thumb</th>
                            <th>Name</th>
                            <th>SKU</th>
                            <th>Price</th>
                            <th>Remove</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php
                            $i = 1;
                        @endphp
                        @foreach ($products as $pro)
                            <tr>
                                <td>{{ $i }}</td>
                                <td class="product-thumb">
                                    <img src="{{ getProductImage($pro->product_image) }}" alt="{{ $pro->name}}">
                                </td>
                                <td>{{ $pro->name }}</td>
                                <td>{{ $pro->sku }}</td>
                                <td>{{ formatPrice($pro->price) }}</td>
                                
                                <td class="table-actions">
                                    <form action="{{ route('category.product.remove', ['proId'=> $pro->id, 'catId' => $category->id]) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="" onclick="return confirm('Are you sure?')"><i class="fas fa-trash-alt"></i><span>remove</span></button>
                                        
                                    </form>
                                </td>
                            </tr>
                            @php
                                $i++;
                            @endphp

                            @endforeach

                        </tbody>
                    </table>
                    @else
                        <h3 class="no-items">There are no products in this category.</h3>
                    @endif

                </div>
            </div>
        </div>
    <div class="add-new-product">
        {{-- <button id="show-modal" class="btn btn-primary" @click="showModalFunc(11)"><i class="fas fa-plus"></i> Add New Product</button>
        <!-- use the modal component, pass in the prop -->
        <modal v-if="showModal" @close="closeModal" :products="products">

        </modal> --}}
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master', ['subtitle' => 'Categories'])

@section('content')
<section id="product-list">
    <div class="card card-big">
        <div class="card-body">
            <h5 class="card-title">List of categories</h5>
            <div class="table-responsive">

                <table class="table center-aligned-table list-categories">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>No. of products</th>
                        <th>Slug</th>
                        <th>Depth</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php
                    $i = 1;
                    @endphp
                    @forelse ($categories as $cat)
                        <tr>
                            <td>{{ $i }}</td>
                            <td>{{ $cat->name }}</td>
                            <td>{{ adminGetProductNumber($cat->id) }}</td>
                            <td>{{ $cat->slug }}</td>
                            <td><span class="badge badge-blue">Root</span></td>
                            <td class="table-actions">
                                <a href="{{ route('categories.edit', $cat->id) }}" class="btn-outline btn-sm"><i class="fas fa-edit"></i></a>
                                <form action="{{ route('categories.destroy', $cat->id)}}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                    <button type="submit" onclick="return confirm('Are you sure for this action? All child categories will be deleted also.')"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                            </td>
                        </tr>
                        @php
                            $i++;
                        @endphp
                        @foreach($cat->children as $ca)
                            <tr>
                                <td>{{ $i }}</td>
                                <td>- {{ $ca->name }}</td>
                                <td>{{ adminGetProductNumber($ca->id) }}</td>
                                <td>{{ $ca->slug }}</td>
                                <td><span>1st</span></td>
                                <td class="table-actions">
                                    <a href="{{ route('categories.edit', $ca->id) }}" class="btn-outline btn-sm"><i class="fas fa-edit"></i></a>
                                    <form action="{{ route('categories.destroy', $ca->id)}}" method="POST">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                    <button type="submit" onclick="return confirm('Are you sure for this action? All child categories will be deleted also.')"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @php
                                $i++;
                            @endphp
                            @foreach($ca->children as $lastChild)
                                <tr>
                                    <td>{{ $i }}</td>
                                    <td>- - {{ $lastChild->name }}</td>
                                    <td>{{ adminGetProductNumber($lastChild->id) }}</td>
                                    <td>{{ $lastChild->slug }}</td>
                                    <td><span>2nd</span></td>
                                    <td class="table-actions">
                                        <a href="{{ route('categories.edit', $lastChild->id) }}" class="btn-outline btn-sm"><i class="fas fa-edit"></i></a>
                                        <form action="{{ route('categories.destroy', $lastChild->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        <button type="submit" onclick="return confirm('Are you sure for this action? All child categories will be deleted also.')"><i class="fas fa-trash-alt"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @php
                                    $i++;
                                @endphp
                            @endforeach
                        @endforeach
                    @empty

                        There is no categories yet.

                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

@endsection